[package]
name = "rust-discord-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
dotenv = "0.15.0"
once_cell = "1.21.3"
poise = "0.6.1"
regex = "1.12.2"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
unescape = "0.1.0"
